---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    D: true
    vv: true
platforms:
  - name: debian10
    image: docker.io/pycontribs/debian:10
    pre_build_image: true
  - name: centos8
    image: docker.io/pycontribs/debian:11
    pre_build_image: true
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    #published_ports:
    #  - "0.0.0.0:8080:8080/tcp"
    #  - "[::]:8080:8080/tcp"
provisioner:
  name: ansible
  options:
    D: true
    vv: true
  playbooks:
    converge: ../resources/converge.yml
    verify: ../resources/verify.yml
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
...
